name: build
on:
  push:
  pull_request:
  workflow_dispatch:
permissions: {}
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get install -y --no-install-recommends clang-format-15 doxygen
      - uses: actions/checkout@v4
      - name: Check code style
        run: |
          mk/format-code.sh
          git diff --exit-code
      - uses: arduino/compile-sketches@v1
        with:
          fqbn: esp32:esp32:esp32cam
          libraries: |
            - source-path: ./
            - source-url: https://github.com/me-no-dev/AsyncTCP.git
              version: 58cbe1fabe78977e3140391c01c03f0cb51e347c
            - source-url: https://github.com/me-no-dev/ESPAsyncWebServer.git
              version: 7f3753454b1f176c4b6d6bcd1587a135d95ca63c
      - name: Build docs
        run: docs/build.sh
      - name: Deploy docs
        uses: nwtgck/actions-netlify@v3
        with:
          publish-dir: ./docs/html/
          production-deploy: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: ${{ github.sha }} ${{ github.run_id }}
          enable-pull-request-comment: false
          enable-commit-comment: false
          enable-commit-status: false
          enable-github-deployment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: 7de100ca-e942-419d-af2c-18e6c528b96e
        if: ${{ github.repository == 'yoursunny/esp32cam' && github.event_name == 'push' }}
    timeout-minutes: 30
